port: 8081 #监听端空
releaseFlag: false # release 标签
picPath: ../pic

log:
  size: 102400
  dateFlag: true
  path: ../log
  compressFlag: true
  fileName: decoration-backend-server.log
  level: debug # 日志级别panic,fatal,error,warn,info,debug,trace

mySQL:
  name: decoration
  addr: 127.0.0.1:3306 # 数据库主机地址，上线必须修改
  user: root # 数据用户名，上线必须修改
  password: 123456 #  数据库密码，上线必须修改
  poolLimit: 32 # 数据链接数限制
