port: 8081 #监听端空
TLSPort: 443
releaseFlag: false # release 标签

picture:
  savePath: ../upload #文件存放路径
  urlPrefix: http://127.0.0.1:8081 # url 地址前缀
  urlRelativePath: upload/ #url 相对路径

log:
  size: 102400
  dateFlag: true
  path: ../log
  compressFlag: true
  fileName: decoration-backend-server.log
  level: debug # 日志级别panic,fatal,error,warn,info,debug,trace

mySQL:
  name: decoration
  addr: 127.0.0.1:3306 # 数据库主机地址，上线必须修改
  user: root # 数据用户名，上线必须修改
  password: 123456 #  数据库密码，上线必须修改
  poolLimit: 32 # 数据链接数限制

auth:
  signKey: JerrySignedKey
  CRTPath: decoration.pem #证书路径
  privateKeyPath: decoration-key.pem #私钥路径
